apiVersion: v1
kind: Deployment
metadata:
  name: ta-php
  labels:
    name: ta-php
spec:
  containers:
  - name: ta-php
    image: hilmiraditya/ta_php
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9000
    # readinessProbe:
    #   httpGet:
    #     path: /
    #     port: 9000
    #   initialDelaySeconds: 5
    #   periodSeconds: 10
    #   timeoutSeconds: 2
    #   successThreshold: 1
    #   failureThreshold: 3