apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mydata-vs
spec:
  hosts:
  - "*"
  gateways:
  - mydata-gateway
  http:
  - route:
      - destination:
          host: mydata
          port:
            number: 80