version: "3"
services: 
    app:
        container_name: ITSshorturl_app
        working_dir: /var/www
        restart: unless-stopped
        build: 
            context: ./docker/php/
            dockerfile: Dockerfile
        image: php:latest
        volumes: 
            - ./code:/var/www
        networks: 
            - sample-network
        
    nginx:
        container_name: ITSshorturl_nginx
        restart: unless-stopped
        image: nginx:latest
        ports: 
            - "80:80"
        volumes: 
            - ./code:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - sample-network

    mysql:
        image: mysql:5.7
        container_name: ITSshorturl_mysql
        restart: unless-stopped
        volumes:
            - ./docker/mysql:/var/lib/mysql/
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=mydb
            - MYSQL_USER=rahasia
            - MYSQL_PASSWORD=rahasia
            - MYSQL_ROOT_PASSWORD=rahasia
        networks:
            - sample-network
networks: 
    sample-network:
        driver: bridge